#Crie um programa que crie uma matriz de dimensão 3x3 e preencha com valores lidos pelo teclado. No final, mostre a matriz na tela, com formatação correta.
matriz = [],[],[]
matriz[0].append(int(input(f"Digite um valor para [0,0]: ")))
matriz[0].append(int(input(f"Digite um valor para [0,1]: ")))
matriz[0].append(int(input(f"DIgite um valor para [0,2]: ")))
matriz[1].append(int(input(f"Digite um valor para [1,0]: ")))
matriz[1].append(int(input(f"Digite um valor para [1,1]: ")))
matriz[1].append(int(input(f"Digite um valor para [1,2]: ")))
matriz[2].append(int(input(f"Digite um valor para [2,0]: ")))
matriz[2].append(int(input(f"Digite um valor para [2,1]: ")))
matriz[2].append(int(input(f"Digite um valor para [2,2]: ")))
print(f"[{matriz[0][0]}]",end=' ')
print(f"[{matriz[0][1]}]",end=' ')
print(f"[{matriz[0][2]}]",end=' ')
print(f"\n[{matriz[1][0]}]",end=' ')
print(f"[{matriz[1][1]}]",end=' ')
print(f"[{matriz[1][2]}]",end=' ')
print(f"\n[{matriz[2][0]}]",end=' ')
print(f"[{matriz[2][1]}]",end=' ')
print(f"[{matriz[2][2]}]",end=' ')
